/**
 * Backend de Recetario Flor de Azalea.
 * Fuente de verdad: este Google Sheet (tabs Recetas / Ingredientes / Preparacion).
 * Despliegue: Web App, Ejecutar como "Yo", Acceso "Cualquiera".
 */

var SHEET_RECETAS = 'Recetas';
var SHEET_INGREDIENTES = 'Ingredientes';
var SHEET_PREPARACION = 'Preparacion';

var HEADERS_RECETAS = ['receta_id', 'nombre', 'categoria', 'porciones', 'tiempo_prep', 'notas'];
var HEADERS_INGREDIENTES = ['receta_id', 'ingrediente', 'cantidad', 'unidad'];
var HEADERS_PREPARACION = ['receta_id', 'paso_num', 'instruccion'];

var RECETAS_SEED = [
  ["R001", "Agua de Tamarindo", "Aguas", "20 litros", "40 min", "Remojar tamarindo la noche anterior"],
  ["R002", "Agua de Limón", "Aguas", "20 litros", "20 min", ""],
  ["R003", "Agua de Jamaica", "Aguas", "20 litros", "40 min", "Remojar Jamaica la noche anterior"],
  ["R004", "Agua de Pepino", "Aguas", "20 litros", "30 min", "Deslechar pepino para que no amargue"],
  ["R005", "Agua de Mango", "Aguas", "20 litros", "25 min", ""],
  ["R006", "Agua de Melón", "Aguas", "20 litros", "25 min", ""],
  ["R007", "Agua de Guanábana", "Aguas", "20 litros", "25 min", ""],
  ["R008", "Agua de Piña", "Aguas", "20 litros", "25 min", ""],
  ["R009", "Agua de Guayaba", "Aguas", "20 litros", "25 min", ""],
  ["R010", "Agua de Naranja", "Aguas", "20 litros", "30 min", ""],
  ["R011", "Agua de Tuna", "Aguas", "20 litros", "20 min", ""],
  ["R012", "Agua de Sandía", "Aguas", "20 litros", "25 min", ""],
  ["R013", "Agua de Cebada", "Aguas", "20 litros", "20 min", ""],
  ["R014", "Horchata", "Aguas", "20 litros", "25 min", ""],
  ["R015", "Horchata con Plátano", "Aguas", "20 litros", "30 min", ""],
  ["R016", "Piña Colada", "Aguas", "20 litros", "30 min", ""],
  ["R017", "Horchata de Arroz", "Aguas", "20 litros", "8 hrs remojo + 20 min", "Arroz se remoja toda la noche o se cuece 30 min"],
  ["R018", "Agua de Maracuyá", "Aguas", "20 litros", "25 min", ""],
  ["R019", "Salsa", "Cocina base", "4 litros", "35 min", ""],
  ["R020", "Guacamole", "Cocina base", "5 botes mamileros", "35 min", "Se prepara junto con la salsa"],
  ["R021", "Pasta de Frijol", "Cocina base", "4 kilos cocido / 4 litros frito", "3 hrs", "Lavar, cocer, moler y freír"],
  ["R022", "Tasajo Precocido", "Cocina base", "4 kilos", "30 min", "Doble cocción"],
  ["R023", "Cecina Precocida", "Cocina base", "4 kilos", "30 min", "Mismo proceso que tasajo"],
  ["R024", "Chorizo Cocido", "Cocina base", "2 kilos", "20 min", ""],
  ["R025", "Salchicha Preparada", "Cocina base", "2 kilos", "10 min", "Quitar tripa y desmoronar"],
  ["R026", "Milanesa", "Cocina base", "2 kilos", "~1 hr", "Marinado + empanizado + frito"],
  ["R027", "Tinga de Pollo", "Cocina base", "2 kilos", "1 hr", "Requiere pechuga cocida y desmenuzada previamente"],
  ["R028", "Chiles Rellenos", "Cocina base", "50 piezas", "1.5 hrs", "Requiere tinga hecha un día antes"],
  ["R029", "Chiles en Vinagre", "Cocina base", "4 litros", "30 min", ""]
];

var INGREDIENTES_SEED = [
  ["R001", "Azúcar", 1800, "g"],
  ["R001", "Tamarindo", 1, "kilo"],
  ["R001", "Hielo", 2, "kilos"],
  ["R001", "Agua", 17, "litros"],
  ["R002", "Azúcar", 1800, "g"],
  ["R002", "Limón", 1, "kilo"],
  ["R002", "Hielo", 2, "kilos"],
  ["R002", "Agua", 17, "litros"],
  ["R003", "Azúcar", 1950, "g"],
  ["R003", "Jamaica", 400, "g"],
  ["R003", "Hielo", 2, "kilos"],
  ["R003", "Agua", 17, "litros"],
  ["R004", "Azúcar", 1700, "g"],
  ["R004", "Pepino", 2500, "g"],
  ["R004", "Limones grandes", 25, "piezas (o 40 chicos)"],
  ["R004", "Hielo", 2, "kilos"],
  ["R004", "Agua", 17, "litros"],
  ["R005", "Azúcar", 1300, "g"],
  ["R005", "Mango manila o ataulfo", 5, "kilos"],
  ["R005", "Hielo", 2, "kilos"],
  ["R005", "Agua", 17, "litros"],
  ["R006", "Azúcar", 1300, "g"],
  ["R006", "Melón", 1, "pieza grande (cantidad exacta no especificada en manual)"],
  ["R006", "Hielo", 2, "kilos"],
  ["R006", "Agua", 17, "litros"],
  ["R007", "Azúcar", 1400, "g"],
  ["R007", "Pulpa de guanábana", 1, "kilo"],
  ["R007", "Hielo", 2, "kilos"],
  ["R007", "Agua", 17, "litros"],
  ["R008", "Azúcar", 1300, "g"],
  ["R008", "Piñas medianas", 8, "piezas"],
  ["R008", "Hielo", 2, "kilos"],
  ["R008", "Agua", 17, "litros"],
  ["R009", "Azúcar", 1300, "g"],
  ["R009", "Guayaba", 2500, "g"],
  ["R009", "Hielo", 2, "kilos"],
  ["R009", "Agua", 17, "litros"],
  ["R010", "Azúcar", 1400, "g"],
  ["R010", "Naranja", 4, "kilos"],
  ["R010", "Hielo", 2, "kilos"],
  ["R010", "Agua", 17, "litros"],
  ["R011", "Azúcar", 1400, "g"],
  ["R011", "Tuna", 1, "kilo"],
  ["R011", "Hielo", 2, "kilos"],
  ["R011", "Agua", 17, "litros"],
  ["R012", "Azúcar", 1300, "g"],
  ["R012", "Sandía", 10, "kilos"],
  ["R012", "Hielo", 2, "kilos"],
  ["R012", "Agua", 17, "litros"],
  ["R013", "Azúcar", 1300, "g"],
  ["R013", "Cebada", 1, "kilo"],
  ["R013", "Hielo", 2, "kilos"],
  ["R013", "Agua", 17, "litros"],
  ["R014", "Azúcar", 1300, "g"],
  ["R014", "Avena", 750, "g"],
  ["R014", "Chocomilk", 2, "cucharadas soperas"],
  ["R014", "Leche evaporada (lechera)", 375, "g (1 lata)"],
  ["R014", "Leche condensada (clavel)", 720, "g (2 latas)"],
  ["R014", "Hielo", 2, "kilos"],
  ["R014", "Agua", 17, "litros"],
  ["R015", "Azúcar", 1300, "g"],
  ["R015", "Plátano", 2, "kilos"],
  ["R015", "Leche evaporada (lechera)", 375, "g (1 lata)"],
  ["R015", "Leche condensada (clavel)", 720, "g (2 latas)"],
  ["R015", "Vainilla", 0.5, "tapa"],
  ["R015", "Hielo", 2, "kilos"],
  ["R015", "Agua", 17, "litros"],
  ["R016", "Azúcar", 1300, "g"],
  ["R016", "Piña", 3, "piezas"],
  ["R016", "Crema de coco (calahua)", 480, "g (1 lata)"],
  ["R016", "Leche evaporada (lechera)", 375, "g (1 lata)"],
  ["R016", "Leche condensada (clavel)", 360, "g (1 lata)"],
  ["R016", "Hielo", 2, "kilos"],
  ["R016", "Agua", 17, "litros"],
  ["R017", "Azúcar", 1400, "g"],
  ["R017", "Arroz", 1, "kilo"],
  ["R017", "Canela", 100, "g"],
  ["R017", "Leche condensada (clavel)", 720, "g (2 latas)"],
  ["R017", "Leche evaporada (lechera)", 375, "g (1 lata)"],
  ["R017", "Hielo", 2, "kilos"],
  ["R017", "Agua", 17, "litros"],
  ["R018", "Azúcar", 1800, "g"],
  ["R018", "Maracuyá", 1, "kilo"],
  ["R018", "Hielo", 2, "kilos"],
  ["R018", "Agua", 17, "litros"],
  ["R019", "Tomate", 4, "kilos"],
  ["R019", "Chile serrano", 300, "g"],
  ["R019", "Ajo", 12, "dientes"],
  ["R019", "Cebolla mediana", 1, "pieza"],
  ["R019", "Sal", 10, "cucharadas cafeteras"],
  ["R019", "Agua", 0.5, "litro"],
  ["R020", "Aguacate", 1.5, "kilo"],
  ["R020", "Chile jalapeño", 0.75, "pieza (¾)"],
  ["R020", "Ajo", 10, "dientes"],
  ["R020", "Sal", 1, "cucharada cafetera"],
  ["R021", "Frijol", 4, "kilos"],
  ["R021", "Agua", 8, "litros"],
  ["R021", "Cebolla mediana", 1, "pieza"],
  ["R021", "Ajo (cabeza)", 1, "pieza"],
  ["R021", "Aceite", 0.5, "litro"],
  ["R021", "Cebolla mediana (para freír)", 1, "pieza"],
  ["R021", "Ajo (para freír)", 0.5, "cabeza"],
  ["R021", "Sal", 5, "cucharadas cafeteras"],
  ["R022", "Tasajo", 4, "kilos"],
  ["R022", "Ajo", 90, "g"],
  ["R022", "Aceite", 0.5, "litro"],
  ["R023", "Cecina", 4, "kilos"],
  ["R023", "Ajo", 90, "g"],
  ["R023", "Aceite", 0.5, "litro"],
  ["R024", "Chorizo", 2, "kilos"],
  ["R024", "Agua", 0.5, "litro"],
  ["R025", "Salchicha", 2, "kilos"],
  ["R026", "Pechuga de pollo en corte bistec", 2, "kilos"],
  ["R026", "Agua", 100, "ml"],
  ["R026", "Sal", 2, "cucharadas"],
  ["R026", "Ajo", 10, "dientes"],
  ["R026", "Orégano", 1, "cucharada"],
  ["R026", "Huevo", 4, "piezas"],
  ["R026", "Pan molido", 1, "kilo"],
  ["R026", "Aceite (para freír)", 0.75, "(¾ de cacerola)"],
  ["R027", "Tomate", 2, "kilos"],
  ["R027", "Cebolla mediana", 1, "pieza"],
  ["R027", "Ajo", 5, "dientes"],
  ["R027", "Pollo desmenuzado (pechuga cocida)", 2, "kilos"],
  ["R027", "Caldo de pollo", 0.5, "litro"],
  ["R028", "Chiles ya cocidos y abiertos", 50, "piezas"],
  ["R028", "Tinga (pollo)", 2, "kilos"],
  ["R028", "Huevo", 10, "piezas"],
  ["R028", "Harina", 2, "cucharadas"],
  ["R028", "Aceite", 0.25, "(¼)"],
  ["R029", "Chile jalapeño", 4, "kilos"],
  ["R029", "Zanahoria", 2, "kilos"],
  ["R029", "Cebolla", 1, "kilo"],
  ["R029", "Ajo", 90, "g"],
  ["R029", "Pimienta", 10, "g"],
  ["R029", "Laurel", 5, "g"],
  ["R029", "Orégano", 5, "g"],
  ["R029", "Tomillo", 5, "g"],
  ["R029", "Sal", 220, "g"],
  ["R029", "Agua", 1, "litro"],
  ["R029", "Vinagre blanco", 0.75, "(¾)"]
];

var PREPARACION_SEED = [
  ["R001", 1, "Licuar 1800 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R001", 2, "Lavar 1 kilo de tamarindo y dejar remojando toda la noche"],
  ["R001", 3, "Al día siguiente, licuar a velocidad No. 1 y colar en un colador fino"],
  ["R001", 4, "Quitar la semilla y volver a licuar la pulpa hasta que quede bien molida"],
  ["R001", 5, "Agregar la mezcla en el vitrolero"],
  ["R001", 6, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R002", 1, "Licuar 1800 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R002", 2, "Lavar con agua y jabón 1 kilo de limón"],
  ["R002", 3, "Exprimir todos los limones en el vitrolero"],
  ["R002", 4, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R003", 1, "Licuar 1950 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R003", 2, "Lavar 400 gr de Jamaica y dejar remojando toda la noche"],
  ["R003", 3, "Al día siguiente, hervir la Jamaica por media hora"],
  ["R003", 4, "Colar el concentrado de Jamaica en un colador fino dentro del vitrolero"],
  ["R003", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R004", 1, "Licuar 1700 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R004", 2, "Lavar con agua y jabón 2500 gr de pepino"],
  ["R004", 3, "Deslechar el pepino: cortar la punta y tallarla hasta sacar el líquido blanco para que no amargue"],
  ["R004", 4, "Pelar todos los pepinos, dejando dos con cáscara para darle color al agua"],
  ["R004", 5, "Licuar los pepinos pelados y echar el concentrado al vitrolero sin colar"],
  ["R004", 6, "Licuar los dos pepinos con cáscara y colar en un colador fino en el vitrolero"],
  ["R004", 7, "Lavar con agua y jabón los limones chicos"],
  ["R004", 8, "Exprimir el limón en el vitrolero"],
  ["R004", 9, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R005", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R005", 2, "Lavar con agua y jabón 5 kilos de mango"],
  ["R005", 3, "Pelar y cortar la pulpa del mango"],
  ["R005", 4, "Licuar y colar la pulpa del mango en un colador fino en el vitrolero"],
  ["R005", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R006", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R006", 2, "Lavar con agua y jabón el melón"],
  ["R006", 3, "Pelar y cortar la pulpa del melón"],
  ["R006", 4, "Licuar y colar la pulpa del melón en un colador fino en el vitrolero"],
  ["R006", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R007", 1, "Licuar 1400 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R007", 2, "Licuar a velocidad No. 1 el kilo de pulpa de guanábana"],
  ["R007", 3, "Colar el concentrado en un colador fino en el vitrolero"],
  ["R007", 4, "Sacar la semilla y volver a licuar la pulpa bien molida"],
  ["R007", 5, "Colar la pulpa en un colador fino en el vitrolero"],
  ["R007", 6, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R008", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R008", 2, "Limpiar y lavar con agua y jabón las 8 piñas"],
  ["R008", 3, "Picar la piña en trozos chicos"],
  ["R008", 4, "Licuar y colar la piña en un colador fino en el vitrolero"],
  ["R008", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R009", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R009", 2, "Lavar con agua y jabón 2500 gr de guayaba"],
  ["R009", 3, "Picar la guayaba"],
  ["R009", 4, "Licuar y colar el concentrado de guayaba en un colador fino en el vitrolero"],
  ["R009", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R010", 1, "Licuar 1400 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R010", 2, "Lavar con agua y jabón 4 kilos de naranja"],
  ["R010", 3, "Cortar a la mitad la naranja y exprimir en el extractor"],
  ["R010", 4, "Colar el jugo de naranja en el vitrolero con un colador grueso"],
  ["R010", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R011", 1, "Licuar 1400 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R011", 2, "Pelar 1 kilo de tuna"],
  ["R011", 3, "Licuar a velocidad baja"],
  ["R011", 4, "Vaciar el concentrado en el vitrolero"],
  ["R011", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R012", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R012", 2, "Lavar con agua y jabón 10 kilos de sandía"],
  ["R012", 3, "Pelar y picar la sandía"],
  ["R012", 4, "Licuar y colar la sandía en un colador fino"],
  ["R012", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R013", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R013", 2, "Licuar 1 kilo de cebada y vaciar el concentrado en el vitrolero"],
  ["R013", 3, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R014", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R014", 2, "Licuar 750 gr de avena"],
  ["R014", 3, "Colar el concentrado de avena en un colador fino en el vitrolero"],
  ["R014", 4, "Licuar 2 cucharadas de chocomilk, 1 lechera y 2 leches clavel"],
  ["R014", 5, "Vaciar el concentrado en el vitrolero"],
  ["R014", 6, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R015", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R015", 2, "Pelar 2 kilos de plátano"],
  ["R015", 3, "Licuar y colar el concentrado de plátano en un colador fino"],
  ["R015", 4, "Licuar 1 lata de lechera, 2 latas de clavel y ½ tapa de vainilla"],
  ["R015", 5, "Vaciar el concentrado en el vitrolero"],
  ["R015", 6, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R016", 1, "Licuar 1300 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R016", 2, "Lavar con agua y jabón y pelar 3 piñas"],
  ["R016", 3, "Picar la piña en cuadros medianos"],
  ["R016", 4, "Licuar y colar el concentrado de piña en un colador fino en el vitrolero"],
  ["R016", 5, "Licuar 1 lata de calahua, 1 lata de lechera y 1 lata de leche clavel y vaciar al vitrolero"],
  ["R016", 6, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R017", 1, "Licuar 1300-1400 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R017", 2, "Lavar 1 kilo de arroz y dejar remojando toda la noche, o cocer por 30 minutos"],
  ["R017", 3, "Licuar el arroz cocido con 100 gr de canela y colar el concentrado con un colador fino en el vitrolero"],
  ["R017", 4, "Licuar 2 latas de leche clavel y 1 lata de lechera y vaciar al vitrolero"],
  ["R017", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R018", 1, "Licuar 1800 gr de azúcar y colar en un colador fino al vitrolero de 20 litros"],
  ["R018", 2, "Lavar con agua y jabón 1 kilo de maracuyá"],
  ["R018", 3, "Despulpar el maracuyá"],
  ["R018", 4, "Licuar la pulpa del maracuyá y colar el concentrado en un colador fino"],
  ["R018", 5, "Agregar 2 bolsas de kilo de hielo y agua hasta llenar el vitrolero"],
  ["R019", 1, "Poner a hervir 4 kilos de tomate con medio litro de agua"],
  ["R019", 2, "Asar en el comal 300 gramos de chile serrano con 12 dientes de ajo y 1 cebolla mediana"],
  ["R019", 3, "Una vez cocido todo, licuar"],
  ["R019", 4, "Hervir y sazonar con sal (10 cucharadas cafeteras)"],
  ["R019", 5, "Dejar enfriar y meter en topperes de 2 litros"],
  ["R020", 1, "Lavar 1 kilo y ½ de aguacate, ¾ de chile jalapeño y 10 dientes de ajo"],
  ["R020", 2, "Moler en la licuadora con 1 cucharada cafetera de sal por vaso"],
  ["R020", 3, "Llenar 5 botes mamileros para pasar a mesa"],
  ["R020", 4, "Lo que sobra se mete al refrigerador en topperes"],
  ["R021", 1, "Lavar 4 veces el frijol"],
  ["R021", 2, "Poner a cocer 4 kilos en 8 litros de agua con 1 cabeza de ajo y 1 cebolla mediana hasta que se cueza"],
  ["R021", 3, "Moler el frijol cocido en la licuadora"],
  ["R021", 4, "Freír en dos ollas (2 kilos cada una) con ¼ de aceite por cada 2 litros"],
  ["R021", 5, "Agregar cebolla y ajo picados por cada 2 kilos de frijol, hasta que doren"],
  ["R021", 6, "Agregar 5 cucharadas cafeteras de sal por olla"],
  ["R021", 7, "Dejar hervir 10 minutos más, enfriar y almacenar en topperes de 2 litros"],
  ["R022", 1, "Lavar 4 kilos de tasajo"],
  ["R022", 2, "Precocer en cacerola por 15 minutos"],
  ["R022", 3, "Dejar enfriar y rebanar en trozos de 1 cm"],
  ["R022", 4, "Volver a cocer con 90 gr de ajo y medio litro de aceite por 15 minutos"],
  ["R022", 5, "Dejar enfriar y guardar en topper al refrigerador de almacén"],
  ["R023", 1, "Precocer 4 kilos de cecina en cacerola por 15 minutos"],
  ["R023", 2, "Dejar enfriar y rebanar en trozos de 1 cm"],
  ["R023", 3, "Volver a cocer con 90 gr de ajo y medio litro de aceite por 15 minutos"],
  ["R023", 4, "Dejar enfriar y guardar en topper de 4 kg al refrigerador de almacén"],
  ["R024", 1, "Poner a cocer 2 kilos de chorizo con medio litro de agua por 20 minutos"],
  ["R024", 2, "Guardar en topperes de 1 kilo"],
  ["R025", 1, "Quitar la tripa a 2 kilos de salchicha"],
  ["R025", 2, "Desmoronar"],
  ["R025", 3, "Guardar en bolsas de medio kilo"],
  ["R026", 1, "Lavar 2 kilos de pechuga de pollo en corte bistec"],
  ["R026", 2, "Moler en la licuadora 100 ml de agua, 2 cucharadas de sal, 10 dientes de ajo y 1 cucharada de orégano"],
  ["R026", 3, "Vaciar la mezcla en un topper extendido y pasar cada bistec por el marinado"],
  ["R026", 4, "Quebrar y disolver 4 huevos en un plato"],
  ["R026", 5, "Pasar cada bistec marinado en el huevo y después en el pan molido"],
  ["R026", 6, "Meter en topperes de 1 kilo y guardar en almacén"],
  ["R026", 7, "Freír en cacerola con ¾ de aceite, 1 a 2 piezas según tamaño"],
  ["R026", 8, "Escurrir en servitoallas y dejar lista para barra de producción"],
  ["R027", 1, "Rebanar en cuadritos 2 kilos de tomate, 1 cebolla mediana y 5 ajos picados"],
  ["R027", 2, "Freír ajo y cebolla, agregar tomate hasta que dore"],
  ["R027", 3, "Agregar el pollo deshebrado (pechuga previamente cocida y desmenuzada)"],
  ["R027", 4, "Agregar medio litro de caldo de pollo"],
  ["R027", 5, "Hervir por 25 minutos"],
  ["R027", 6, "Dejar enfriar y guardar en topperes de 1 kilo"],
  ["R028", 1, "Considerar que la tinga debe estar hecha un día antes"],
  ["R028", 2, "Rellenar 50 chiles ya cocidos y abiertos con 40 gramos (1 cucharada sopera) de tinga cada uno"],
  ["R028", 3, "Hacer espuma quebrando 10 claras de huevo, con la yema y 2 cucharadas de harina aparte"],
  ["R028", 4, "Calentar ¼ de aceite en un sartén"],
  ["R028", 5, "Pasar los chiles por la espuma y freír"],
  ["R028", 6, "Escurrir los chiles y acomodar en topperes de 25 chiles cada uno"],
  ["R028", 7, "Una vez fríos, llevar al refrigerador"],
  ["R029", 1, "Freír en ¼ de aceite la cebolla por 1 minuto"],
  ["R029", 2, "Agregar los chiles jalapeños"],
  ["R029", 3, "Moler los demás ingredientes (ajo, pimienta, laurel, orégano, tomillo, sal) con 1 litro de agua y colar"],
  ["R029", 4, "Agregar el litro de agua colado y ¾ de vinagre blanco"],
  ["R029", 5, "Hervir por 25 minutos"],
  ["R029", 6, "Agregar la zanahoria junto con los demás ingredientes y apagar"]
];

function ensureSetup_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  ensureSheetWithHeaders_(ss, SHEET_RECETAS, HEADERS_RECETAS, RECETAS_SEED);
  ensureSheetWithHeaders_(ss, SHEET_INGREDIENTES, HEADERS_INGREDIENTES, INGREDIENTES_SEED);
  ensureSheetWithHeaders_(ss, SHEET_PREPARACION, HEADERS_PREPARACION, PREPARACION_SEED);
}

function ensureSheetWithHeaders_(ss, name, headers, seedRows) {
  var sheet = ss.getSheetByName(name);
  if (!sheet) {
    sheet = ss.insertSheet(name);
  }
  var firstRow = sheet.getRange(1, 1, 1, headers.length).getValues()[0];
  var hasHeaders = headers.every(function (h, i) { return firstRow[i] === h; });
  if (!hasHeaders) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  }
  if (seedRows.length && sheet.getLastRow() < 2) {
    sheet.getRange(2, 1, seedRows.length, headers.length).setValues(seedRows);
  }
}

function sheetToObjects_(sheet) {
  var values = sheet.getDataRange().getValues();
  var headers = values[0];
  var rows = values.slice(1).filter(function (row) {
    return row.some(function (cell) { return cell !== ''; });
  });
  return rows.map(function (row) {
    var obj = {};
    headers.forEach(function (h, i) { obj[h] = row[i]; });
    return obj;
  });
}

function doGet(e) {
  ensureSetup_();
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var payload = {
    recetas: sheetToObjects_(ss.getSheetByName(SHEET_RECETAS)),
    ingredientes: sheetToObjects_(ss.getSheetByName(SHEET_INGREDIENTES)),
    preparacion: sheetToObjects_(ss.getSheetByName(SHEET_PREPARACION))
  };
  return ContentService
    .createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}
